server:
  port: 8082

spring:
  application:
    name: desafio-itau

management:
  endpoints:
    web:
      exposure:
        include: 'health,info,prometheus,metrics'
  observations:
    key-values:
      application: desafio-itau
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/span

springdoc:
  swagger-ui:
    path: /desafio-api.html
