global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "desafio-itau-job"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["host.docker.internal:8082"]
        labels:
          application: "desafio-itau"